[server]
ip_or_domain = "teamserver.com"
port = 80

[smtp]
server = "smtp.126.com"
username = "xxx@126.com"
from_email = "Test <xxx@126.com>"
subject = "Test Subject"
interval = 5

[email]
template = "template.html"
original_appendix_path_exe = "./appendix.exe"
appendix_name_for_sending_exe = "xxx"
original_appendix_path_lnk = "./appendix.lnk"
appendix_name_for_sending_lnk = "xxx"
zip_name = "xxx"
