[server]
ip = "127.0.0.1"
port = 8080

[paths]
phish_page = "./frontend/test.html"
redirect_url = "http://localhost:8080/success"
success_page = "./frontend/success.html"

[smtp]
server = "smtp.126.com"
username = "xxx@126.com"
from_email = "Test <xxx@126.com>"
subject = "Test Subject"
interval = 5

[email]
template = "template.html"