name: Cross-Platform Release

on:
  push:
    tags:
      - "v*"

env:
  RUST_TOOLCHAIN: stable
  CARGO_MAKE_VERSION: 0.36.23

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          targets: |
            x86_64-pc-windows-msvc
            x86_64-pc-windows-gnu
            x86_64-unknown-linux-gnu

      - name: Install Linux Cross-Compiler
        run: |
          choco install -y mingw --params "/InstallDir:C:/msys64"
          C:/msys64/msys2_shell.cmd -c "pacman -Syu --noconfirm --needed mingw-w64-x86_64-gcc"
          echo "CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=C:/msys64/mingw64/bin/x86_64-linux-gnu-gcc" >> $env:GITHUB_ENV

      - name: Install Visual Studio Build Tools
        run: |
          choco install -y visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"

      - name: Install cargo-make
        run: cargo install cargo-make --version ${{ env.CARGO_MAKE_VERSION }}

      - name: Run Full Build
        run: cargo make bin

      - name: Verify Build Output
        run: |
          Test-Path -Path bin/client/client-x86_64-windows-pc-gnu.exe
          Test-Path -Path bin/server/server-x86_64-unknown-linux-gnu

      - uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: ${{ github.workspace }}/bin
          retention-days: 1

  release:
    name: Create Release
    needs: build
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: binaries
          path: bin

      - name: Package Binaries
        run: |
          Compress-Archive -Path bin/client/* -DestinationPath client.zip
          Compress-Archive -Path bin/server/* -DestinationPath server.zip

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            client.zip
            server.zip
